using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataBase.EF.ConnectionForWine.Migrations
{
    public partial class InitialDataMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"-- WineReferenceInformations
           INSERT INTO ""WineReferenceInformations"" VALUES (default, 'Для эффективного управления этим процессом и прогнозирования его результатов широко используются различные математические модели. Одной из основных моделей прогнозирования брожения вина является модель ферментации, которая основывается на биохимических реакциях, происходящих в процессе брожения. Эта модель учитывает изменения концентрации сахара, алкоголя, кислот и других компонентов в процессе времени, а также влияние температуры, pH и других факторов на скорость и направление реакций. Другой распространенной моделью является модель Гомпертца, которая описывает кривую роста микроорганизмов во времени. Эта модель хорошо подходит для анализа динамики процесса брожения, учитывая, что брожение вина осуществляется за счет деятельности дрожжей, которые также подчиняются законам роста и размножения. Кроме того, существуют статистические модели, которые используются для анализа и прогнозирования временных рядов, таких как изменение уровня алкоголя, pH и других параметров во времени. Эти модели могут помочь предсказать конечный результат процесса брожения на основе данных о его динамике в прошлом. Современные методы анализа данных, такие как машинное обучение и искусственные нейронные сети, также находят применение в прогнозировании процесса брожения вина. Эти методы могут обрабатывать большие объемы данных и выявлять сложные взаимосвязи между различными параметрами, что помогает улучшить точность прогнозирования и оптимизировать условия производства. В целом, разнообразие математических моделей прогнозирования процесса брожения вина позволяет виноделам эффективно управлять производством, достигать желаемых характеристик и обеспечивать стабильное качество продукции. Применение этих моделей в сочетании с практическим опытом и экспертными знаниями играет ключевую роль в развитии виноделия и создании высококачественных вин.', 1);
           INSERT INTO ""WineReferenceInformations"" VALUES (default, 'Шаптализация вина представляет собой процесс, используемый в виноделии для регулирования уровня сахара в виноградном соке перед началом процесса брожения. Этот метод широко применяется в регионах с прохладным климатом или в годах, когда виноград созревает с недостаточным содержанием сахара для получения качественного вина. Суть процесса заключается в добавлении сахара в сок, чтобы повысить его концентрацию и, следовательно, потенциальный уровень алкоголя в конечном продукте. Обычно для этого используется сахара виноградного или нерафинированного сахара, хотя также могут применяться другие источники сахара. Шаптализация позволяет виноделам контролировать содержание алкоголя и сладости вина, что в свою очередь влияет на его вкусовые характеристики, аромат и стиль. Данный метод также позволяет более точно управлять процессом брожения и получать более предсказуемый конечный результат, особенно в условиях переменного климата или нестабильного урожая. Однако, необходимо учитывать, что шаптализация может повлиять на характер вина, особенно если сахар добавляется в больших количествах. Это может привести к изменению баланса между кислотностью и сладостью, а также влиять на комплексность вкуса и аромата. Кроме того, в некоторых регионах законодательство устанавливает ограничения на использование шаптализации, определяя максимально допустимые уровни сахара, которые можно добавить к вину.', 2);
           INSERT INTO ""WineReferenceInformations"" VALUES (default, 'Купажирование вина представляет собой искусство создания уникального и сбалансированного продукта путем смешивания различных сортов винограда или вин разного происхождения. Этот процесс является одним из ключевых этапов виноделия, где виноделы сочетают вина с целью достижения определенного вкуса, аромата и стиля. Главная цель купажирования заключается в создании вина, которое выделяется высоким качеством и характером, недоступным при использовании отдельных компонентов. Для этого виноделы учитывают множество факторов, включая характеристики винограда, климатические условия урожая, свойства почвы, а также технические параметры производства. В процессе купажирования важно обеспечить сбалансированность вина, где каждый компонент дополняет другие, создавая гармоничное сочетание вкусовых и ароматических нот. Также важно сохранить выразительные характеристики винограда и региона, что придает вину уникальность и подлинность. Купажирование позволяет виноделам контролировать и корректировать характеристики вина, такие как кислотность, сладость, таннинность и структура, чтобы создать идеальный баланс в конечном продукте. Этот процесс также способствует созданию вин с постоянным стилем и качеством, обеспечивая стабильность и непрерывность вкусовых характеристик. Кроме того, купажирование открывает возможности для экспериментов и инноваций, позволяя виноделам создавать новые и уникальные вкусовые профили, а также адаптироваться к изменяющимся рыночным требованиям и вкусам потребителей.', 3);
           INSERT INTO ""WineReferenceInformations"" VALUES (default, 'Крепление вина - это процесс, направленный на увеличение содержания алкоголя в вине путем добавления спиртосодержащего напитка, обычно винного спирта. Этот процесс применяется в виноделии с целью корректировки уровня алкоголя в конечном продукте, а также для придания вину определенных характеристик и стиля. Главная цель крепления вина заключается в достижении определенного уровня алкоголя, который может быть важным для определенных вин или стилей, либо чтобы сделать вино более устойчивым к хранению. Для этого в виноделии используются различные методы, включая добавление чистого спирта или алкогольных напитков, таких как коньяк или бренди. Крепление вина может происходить в различных стадиях производства. Некоторые виноделы предпочитают добавлять спирт в сок винограда до начала процесса брожения, что приводит к созданию так называемого ""фортифицированного"" вина. Другие могут крепить вино после завершения брожения, чтобы сохранить его естественные ароматы и вкусовые характеристики. Одним из самых известных примеров крепленых вин является портвейн, который производится в Португалии и крепится добавлением коньяка. Крепленные вина также включают шерри, мадеру и марсалу, каждое из которых имеет свои уникальные процессы производства и стили. Важно отметить, что крепление вина может оказывать значительное влияние на его вкус, аромат и стиль. Добавление спирта может изменить баланс между сладостью и кислотностью, а также влиять на структуру и тело вина. Поэтому виноделы должны проявлять осторожность и внимательность при применении этого процесса, чтобы сохранить качество и целостность конечного продукта.', 4);

           -- WineTypicalEvents
           INSERT INTO ""WineTypicalEvents"" VALUES (default, 'Шаптализация', 1);
           INSERT INTO ""WineTypicalEvents"" VALUES (default, 'Купажирование', 2);
           INSERT INTO ""WineTypicalEvents"" VALUES (default, 'Крепление', 3);

           -- GrapeVarieties
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Августин (V-25/20)', 17 , 8.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Агадаи', 14.5 , 6.9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Агат донской', 14.3 , 6.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Аг изюм', 19.1 , 7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Ананасный', 21.2 , 6.4);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Белорозовый', 18 , 5);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Богатырский', 18.2 , 6.9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Богларка(КМ-159)', 13.9 , 6.9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Восторг', 16.8 , 6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Декабрьский', 19 , 8.4);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Десертный', 19.6 , 7.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default,'Дольчатый', 13.4 , 9.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Донская роза', 18.1 , 7.2);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Донской алый', 17.9 , 8.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Жемчуг Саба', 18.4 , 6.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Зоревой', 17.5 , 5.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Карабурну', 18.2 , 7.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Карамол', 16.3 , 6.8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Кишмиш лучистый', 15.7 , 7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Кишмиш черный', 22.2 , 6.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Кодрянка', 16.2 , 6.8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Королева виноградников', 16 , 6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Крымская жемчужина', 18.2 , 8.1);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Кутузовский', 15.7 , 10.1);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Ляна', 17.8 , 7.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мадлен Анжевин', 16.8 , 6.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Май-гуй-Сан', 20.2 , 7.5);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мискет дунавски', 16.9 , 7.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Молдова', 15.6 , 11.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Муромец', 15.9 , 7.2);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мускат гамбургский', 21.6 , 7.8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мускат дербентский', 17.6 , 8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мускат узбекистанский', 19 , 7.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Мускат янтарный', 17.7 , 7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Осенний черный', 16 , 10.8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Особый', 17 , 6.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Памяти Котовского', 16.6 , 10.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Перла Бухареста', 16.2 , 9.2);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Пестроцветный', 17 , 6.8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Пионер Одессы', 14.3 , 6.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Премьер', 17.5 , 5.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Ромулус', 21.6 , 6.9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Русбол', 16.6 , 7.4);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Русмол', 15.6 , 8.2);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Сверхранний волгодонскии', 16.4 , 9.2);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Сенека', 17.6 , 6.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Сенсо', 19.6 , 8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Скоренский красный', 15.2 , 9.4);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Стелла', 17.7 , 9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Тавриз', 19.9 , 6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Тавроси', 17.8 , 9.9);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Таировский огонек', 17 , 8);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Танаис', 16.9 , 7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Тасон', 16.8 , 5.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Томайский', 17.5 , 6.6);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Урожайный', 14.1 , 9.4);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Фрумоаса албэ', 18.1 , 6.5);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Шасла белая', 16.9 , 6.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Шасла мускатная', 17.1 , 6.7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Шасла розовая', 18.1 , 7);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Южный (V-72-58)', 16.5 , 10.3);
           INSERT INTO ""GrapeVarieties"" VALUES(default, 'Яловенский столовый', 17 , 9.1);

           --AreometrDefaultValues
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1034, 6.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1035, 6.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1036, 6.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1037, 7.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1038, 7.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1039, 7.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1040, 8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1041, 8.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1042, 8.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1043, 8.7);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1044, 9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1045, 9.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1046, 9.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1047, 9.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1048, 10);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1049, 10.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1050, 10.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1051, 10.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1052, 11.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1053, 11.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1054, 11.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1055, 11.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1056, 12.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1057, 12.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1058, 12.7);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1059, 13);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1060, 13.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1061, 13.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1061, 13.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1062, 14);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1063, 14.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1070, 15.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1071, 16.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1072, 16.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1073, 16.7);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1074, 17);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1075, 17.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1076, 17.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1077, 17.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1078, 18);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1079, 18.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1080, 18.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1081, 18.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1082, 19.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1083, 19.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1084, 19.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1085, 19.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1086, 20.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1087, 20.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1088, 20.7);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1089, 21);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1090, 21.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1091, 21.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1092, 21.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1093, 22);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1094, 22.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1095, 22.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1096, 22.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1097, 23.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1098, 23.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1099, 23.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1100, 23.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1105, 25.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1106, 25.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1107, 25.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1108, 26);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1109, 26.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1110, 26.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1111, 26.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1112, 27.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1113, 27.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1114, 27.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1115, 27.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1116, 28.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1117, 28.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1118, 28.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1119, 29);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1120, 29.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1121, 29.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1122, 29.8);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1123, 30.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1124, 30.3);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1125, 30.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1126, 30.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1127, 31.1);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1128, 31.4);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1129, 31.6);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1130, 31.9);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1131, 32.2);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1132, 32.5);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1133, 32.7);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1134, 33);
           INSERT INTO ""AreometrDefaultValues"" VALUES (default, 1135, 33.3);

           -- DifferenceAreometrDefaultValues
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 1 , 0.2 , 0.15);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 2 , 0.45 , 0.25);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 3 , 0.65 , 0.4);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 4 , 0.9 , 0.5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 5 , 1.1 , 0.65);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 6 , 1.35 , 0.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 7 , 1.55 , 0.9);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 8 , 1.75 , 1.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 9 , 2 , 1.2);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 10 , 2.2 , 1.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 11 , 2.45 , 1.45);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 12 , 2.65 , 1.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 13 , 2.9 , 1.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 14 , 3.1 , 1.85);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 15 , 3.3 , 1.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 16 , 3.55 , 2.1);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 17 , 3.75 , 2.25);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 18 , 4 , 2.35);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 19 , 4.2 , 2.5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 20 , 4.45 , 2.6);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 21 , 4.65 , 2.75);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 22 , 4.85 , 2.9);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 23 , 5.1 , 3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 24 , 5.3 , 3.15);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 25 , 5.55 , 3.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 26 , 5.75 , 3.4);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 27 , 6 , 3.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 28 , 6.2 , 3.65);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 29 , 6.4 , 3.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 30 , 6.65 , 3.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 31 , 6.85 , 4.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 32 , 7.1 , 4.2);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 33 , 7.3 , 4.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 34 , 7.55 , 4.45);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 35 , 7.75 , 4.6);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 36 , 7.95 , 4.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 37 , 8.2 , 4.85);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 38 , 8.4 , 5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 39 , 8.65 , 5.1);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 40 , 8.85 , 5.25);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 41 , 9.1 , 5.35);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 42 , 9.3 , 5.5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 43 , 9.5 , 5.65);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 44 , 9.75 , 5.75);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 45 , 9.95 , 5.9);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 46 , 10.2 , 6.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 47 , 10.4 , 6.15);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 48 , 10.65 , 6.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 49 , 10.85 , 6.4);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 50 , 11.05 , 6.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 51 , 11.3 , 6.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 52 , 11.5 , 6.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 53 , 11.75 , 6.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 54 , 11.95 , 7.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 55 , 12.2 , 7.2);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 56 , 12.4 , 7.35);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 57 , 12.6 , 7.5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 58 , 12.8 , 7.65);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 59 , 13 , 7.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 60 , 13.2 , 7.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 61 , 13.4 , 8.1);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 62 , 13.6 , 8.25);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 63 , 13.8 , 8.4);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 64 , 14 , 8.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 65 , 15.25 , 8.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 66 , 14.6 , 8.75);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 67 , 14.85 , 8.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 68 , 15.05 , 8.9);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 69 , 15.3 , 9.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 70 , 15.5 , 9.15);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 71 , 15.7 , 9.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 72 , 15.95 , 9.45);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 73 , 16.15 , 9.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 74 , 16.4 , 9.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 75 , 16.6 , 9.85);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 76 , 16.85 , 9.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 77 , 17.05 , 10.1);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 78 , 17.25 , 10.2);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 79 , 17.5 , 10.35);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 80 , 17.7 , 10.5);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 81 , 17.95 , 10.6);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 82 , 18.15 , 10.75);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 83 , 18.4 , 10.85);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 84 , 18.6 , 11);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 85 , 18.8 , 11.15);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 86 , 19.05 , 11.25);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 87 , 19.25 , 11.4);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 88 , 19.5 , 11.55);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 89 , 19.7 , 11.65);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 90 , 19.95 , 11.8);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 91 , 20.15 , 11.9);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 92 , 20.35 , 12.05);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 93 , 20.6 , 12.2);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 94 , 20.8 , 12.3);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 95 , 21.05 , 12.45);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 96 , 21.25 , 12.6);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 97 , 21.45 , 12.7);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 98 , 21.7 , 12.85);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 99 , 21.9 , 12.95);  
           INSERT INTO ""DifferenceAreometrDefaultValues"" VALUES (default , 100 , 22.15 , 13.1);");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
            @"DELETE FROM ""AreometrDefaultValues"";
		    DELETE FROM ""GrapeVarieties"";
		    DELETE FROM ""WineUsers"";
		    DELETE FROM ""WineReferenceInformations"";
		    DELETE FROM ""WineTypicalEvents"";
		    DELETE FROM ""DifferenceAreometrDefaultValues"";");
        }
    }
}
